version: '3'

services:

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5433:5433"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    command: -p 5433
